## Advancing into Analytics
#### From Excel to Python & R 

In [1]:
!pwd

/Users/hussainfadlallah/Desktop/Getting_started_with_Python


In [2]:
!plotly --version

/bin/bash: plotly: command not found


In [3]:
!conda activate env2


CondaError: Run 'conda init' before 'conda activate'



In [4]:
!conda install plotly

Channels:
 - defaults
Platform: osx-64
Solving environment: done

# All requested packages already installed.



In [5]:
!which env

/usr/bin/env


In [6]:
!pip install pyxlsb

In [7]:
a = 1 + (-4)

In [8]:
a

-3

In [9]:
b = abs(a)

In [10]:
b

3

In [11]:
d = b - 1

In [12]:
d

2

In [13]:
from random import randint

In [14]:
randint(0, 36)

4

In [15]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


In [16]:
!conda install xlutils

Channels:
 - defaults
Platform: osx-64
Solving environment: done

# All requested packages already installed.



In [17]:
my_list = [1, 2, 3, ['Hussain', True]]

In [18]:
my_list

[1, 2, 3, ['Hussain', True]]

In [19]:
type(my_list)

list

In [20]:
my_list * 2

[1, 2, 3, ['Hussain', True], 1, 2, 3, ['Hussain', True]]

In [21]:
my_list2 = [4, 1, 5, 2]
for i in my_list2:
    print( i *2)

#my_list2



8
2
10
4


In [22]:
import numpy as np

In [23]:
my_array = np.array([4,1,5,2])
my_array

array([4, 1, 5, 2])

In [24]:
type(my_array)

numpy.ndarray

In [25]:
my_array * 2

array([ 8,  2, 10,  4])

In [26]:
import math

In [27]:
np.round( np.sqrt(my_array), 3)

array([2.   , 1.   , 2.236, 1.414])

In [28]:
my_array

array([4, 1, 5, 2])

In [29]:
 my_array[0],my_array[1]

(4, 1)

In [30]:
my_array[0:2]

array([4, 1])

In [31]:
import pandas as pd

In [32]:
record_1 = np.array(['Jack', 72, False])
record_2 = np.array(['Jill', 65, True])
record_3 = np.array(['Billy', 68, False])
record_4 = np.array(['Susie', 69, False])
record_5 = np.array(['Johnny', 66, False])

In [33]:
roster =  pd.DataFrame(data = [record_1,record_2,record_3,record_4,record_5], 
                      columns = ['Name','Hieght','Injury'], index=['player_1','player_2','player_3','player_4','player5'])

roster

Name Hieght Injury
player_1    Jack     72  False
player_2    Jill     65   True
player_3   Billy     68  False
player_4   Susie     69  False
player5   Johnny     66  False

In [34]:
import seaborn as sns

In [35]:
iris =sns.load_dataset('iris')

In [45]:
iris

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [37]:
iris.head() # the first five rows ...

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [38]:
import os # working with files paths and directories ....

In [39]:
os.path.isfile('worldcities.csv')

True

In [40]:
os.path.isfile('Getting_started_with_Python/worldcities.csv')

False

In [41]:
star = pd.read_excel('worldcities.xlsx')

In [42]:
star.head()

City                   Country    1
0  Rovaniemi                   Finland  2.0
1  Steinkjer                    Norway  3.0
2   Monterey  United States of America  4.0
3       Kuta                 Indonesia  5.0
4      Lovec                  Bulgaria  6.0

In [43]:
star = pd.read_csv('worldcities.csv')

In [44]:
star.head()

City                   Country
0  Rovaniemi                   Finland
1  Steinkjer                    Norway
2   Monterey  United States of America
3       Kuta                 Indonesia
4      Lovec                  Bulgaria

In [46]:
star.info()
# this method will tell us some important things such as dimensions 
# and types of columns ... 

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7322 entries, 0 to 7321
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   City     7322 non-null   object
 1   Country  7322 non-null   object
dtypes: object(2)
memory usage: 114.5+ KB


In [50]:
star.describe()
# this method retreive some describtive statistics 
# in some tables it retreives (mean, median, count, stnd, min, max,25, 50, 75)
# By default, pandas only includes describtive statistics on numeric variables
# We can overrides this with (include = 'all')

City                   Country
count       7322                      7322
unique      7063                       223
top     Victoria  United States of America
freq           5                       769

NaN is a special pandas value to indecate missing or unavaliable data, such as the standard deviation of a categorical variable ....

###  Indexing and Subsetting DataFrames:
Indexing DataFrame is done by accessing the element position by its row and column position.  
To index a DataFrame we can use the (iloc), or integr location, method.  
The square bracket notation will look familiar to you, but this time we need to index by both $Row$ and $Column$ (again both started by zero).   
Let's demonstarte on the roster DataFrame we created before....

In [51]:
roster

Name Hieght Injury
player_1    Jack     72  False
player_2    Jill     65   True
player_3   Billy     68  False
player_4   Susie     69  False
player5   Johnny     66  False

In [53]:
roster.iloc[1, 0]

'Jill'

It is possible to employ slicing here as well to capture multiple rows and columns....  

In [54]:
roster.iloc[1:4, 0:3]

Name Hieght Injury
player_2   Jill     65   True
player_3  Billy     68  False
player_4  Susie     69  False

To index an entire column by name, we can use the related $loc$ method. We'll leave a blank slice in the first index position to capture all rows, then name the column of interest.  

In [57]:
roster.loc[:, 'Name']

player_1      Jack
player_2      Jill
player_3     Billy
player_4     Susie
player5     Johnny
Name: Name, dtype: object

#### Writing Dataframes into tables (Excel & csv):
pandas also includes functions to write DataFrame to both $.csv$ and $.xlsx$ workbooks with the $write_csv()$ and $write_xlsx()$ methods

In [82]:
from pandas import ExcelWriter

In [83]:
file_name = 'Iris_Names.xlsx'

In [84]:
iris.to_excel(file_name)

In [85]:
print(os.getcwd())

/Users/hussainfadlallah/Desktop/Getting_started_with_Python


In [86]:
iris.describe()

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [89]:
iris.to_csv('Iris_Name.csv')

In [90]:
print(os.getcwd())

/Users/hussainfadlallah/Desktop/Getting_started_with_Python


## Exercises :


In [92]:
# 1- Slice the following array so that you are left with the third through fifth elements
practice_array = ['I', 'am', 'having', 'fun', 'with', 'python']
practice_array[2:6]

['having', 'fun', 'with', 'python']

In [93]:
#2- load the tips Dataframe from seaborn.
tips = sns.load_dataset('tips')

In [94]:
tips

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [95]:
# print some information about this DataFrame, such as the number
# of observations and each column's type
tips.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype   
---  ------      --------------  -----   
 0   total_bill  244 non-null    float64 
 1   tip         244 non-null    float64 
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64   
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB


In [96]:
# print the describtive statistics for theis DataFrame (tips)
tips.describe()

total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [101]:
print(os.getcwd())# اللاين دا مهم اوي بالنسبة لي 

/Users/hussainfadlallah/Desktop/Getting_started_with_Python


In [102]:
ais = pd.read_excel('ais.xlsx')

In [103]:
ais

rcc  wcc    hc    hg  ferr    bmi    ssf  pcBfat    lbm     ht    wt  \
0    3.96  7.5  37.5  12.3    60  20.56  109.1   19.75  63.32  195.9  78.9   
1    4.41  8.3  38.2  12.7    68  20.67  102.8   21.30  58.55  189.7  74.4   
2    4.14  5.0  36.4  11.6    21  21.86  104.6   19.88  55.36  177.8  69.1   
3    4.11  5.3  37.3  12.6    69  21.88  126.4   23.66  57.18  185.0  74.9   
4    4.45  6.8  41.5  14.0    29  18.96   80.3   17.64  53.20  184.6  64.6   
..    ...  ...   ...   ...   ...    ...    ...     ...    ...    ...   ...   
197  4.90  7.6  45.6  16.0    90  27.56   67.2   11.79  82.00  183.9  93.2   
198  5.66  8.3  50.2  17.7    38  23.76   56.5   10.05  72.00  183.5  80.0   
199  5.03  6.4  42.7  14.3   122  22.01   47.6    8.51  68.00  183.1  73.8   
200  4.97  8.8  43.0  14.9   233  22.34   60.4   11.50  63.00  178.4  71.1   
201  5.38  6.3  46.0  15.7    32  21.07   34.9    6.26  72.00  190.8  76.7   

    sex   sport  
0     f  B_Ball  
1     f  B_Ball  
2     f  B_Ball  
3     f  B_Ball  
4     f  B_Ball  
..   ..     ...  
197   m  W_Polo  
198   m  Tennis  
199   m  Tennis  
200   m  Tennis  
201   m  Tennis  

[202 rows x 13 columns]

In [104]:
# print the first few rows of this DataFrame
ais.head()

rcc  wcc    hc    hg  ferr    bmi    ssf  pcBfat    lbm     ht    wt sex  \
0  3.96  7.5  37.5  12.3    60  20.56  109.1   19.75  63.32  195.9  78.9   f   
1  4.41  8.3  38.2  12.7    68  20.67  102.8   21.30  58.55  189.7  74.4   f   
2  4.14  5.0  36.4  11.6    21  21.86  104.6   19.88  55.36  177.8  69.1   f   
3  4.11  5.3  37.3  12.6    69  21.88  126.4   23.66  57.18  185.0  74.9   f   
4  4.45  6.8  41.5  14.0    29  18.96   80.3   17.64  53.20  184.6  64.6   f   

    sport  
0  B_Ball  
1  B_Ball  
2  B_Ball  
3  B_Ball  
4  B_Ball

 write just the sport column of this DataFrame back to excel as $sport.xlsx$

In [117]:
Ais = ais.loc[:,'sport']

In [118]:
Ais

0      B_Ball
1      B_Ball
2      B_Ball
3      B_Ball
4      B_Ball
        ...  
197    W_Polo
198    Tennis
199    Tennis
200    Tennis
201    Tennis
Name: sport, Length: 202, dtype: object

In [119]:
Ais.to_excel('sport.xlsx')

In [120]:
print(os.getcwd())

/Users/hussainfadlallah/Desktop/Getting_started_with_Python


In [121]:
os.chdir('/Users/hussainfadlallah/Desktop/MyOwnBusiness/Data Scientist track/Data Analysis using Python')

In [122]:
print(os.getcwd())

/Users/hussainfadlallah/Desktop/MyOwnBusiness/Data Scientist track/Data Analysis using Python


In [123]:
Ais.to_csv('sport.csv')